<?php

/**
 * Travelport Universal API — Air & related operations catalog.
 *
 * @see https://support.travelport.com/webhelp/uapi/Content/Getting_Started/Easy_Overview/Complete_Services_List.htm
 */
return [
    'groups' => [
        'shop' => ['label' => 'Shop & search', 'icon' => 'fa-search', 'order' => 1],
        'price' => ['label' => 'Price & rules', 'icon' => 'fa-tag', 'order' => 2],
        'book' => ['label' => 'Book & PNR', 'icon' => 'fa-ticket-alt', 'order' => 3],
        'ticket' => ['label' => 'Ticket & refund', 'icon' => 'fa-receipt', 'order' => 4],
        'manage' => ['label' => 'Change & cancel', 'icon' => 'fa-exchange-alt', 'order' => 5],
        'extras' => ['label' => 'Seats & extras', 'icon' => 'fa-chair', 'order' => 6],
    ],

    'operations' => [
        'low_fare_search' => [
            'label' => 'Low Fare Search',
            'description' => 'Search published fares across carriers (primary shopping).',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'LowFareSearchReq',
            'response' => 'LowFareSearchRsp',
            'route' => 'search',
            'status' => 'ready',
        ],
        'availability_search' => [
            'label' => 'Availability Search',
            'description' => 'Flight availability by route and date (schedule-based).',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'AvailabilitySearchReq',
            'response' => 'AvailabilitySearchRsp',
            'status' => 'ready',
        ],
        'air_fare_display' => [
            'label' => 'Fare Display',
            'description' => 'Display fares for a market (city pair).',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'AirFareDisplayReq',
            'response' => 'AirFareDisplayRsp',
            'status' => 'ready',
        ],
        'flight_time_table' => [
            'label' => 'Flight Timetable',
            'description' => 'Timetable between two points.',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'FlightTimeTableReq',
            'response' => 'FlightTimeTableRsp',
            'status' => 'ready',
        ],
        'air_price' => [
            'label' => 'Air Price',
            'description' => 'Price selected itinerary (uses last Low Fare Search in session when available).',
            'group' => 'price',
            'service' => 'air',
            'request' => 'AirPriceReq',
            'response' => 'AirPriceRsp',
            'status' => 'ready',
        ],
        'air_fare_rules' => [
            'label' => 'Fare Rules',
            'description' => 'Retrieve fare rules for a fare basis or priced solution.',
            'group' => 'price',
            'service' => 'air',
            'request' => 'AirFareRulesReq',
            'response' => 'AirFareRulesRsp',
            'status' => 'ready',
        ],
        'air_reprice' => [
            'label' => 'Air Reprice',
            'description' => 'Reprice an existing air itinerary.',
            'group' => 'price',
            'service' => 'air',
            'request' => 'AirRepriceReq',
            'response' => 'AirRepriceRsp',
            'status' => 'beta',
        ],
        'seat_map' => [
            'label' => 'Seat Map',
            'description' => 'Seat map for a flight segment.',
            'group' => 'extras',
            'service' => 'air',
            'request' => 'SeatMapReq',
            'response' => 'SeatMapRsp',
            'status' => 'ready',
        ],
        'air_merchandising' => [
            'label' => 'Merchandising Offers',
            'description' => 'Ancillary / merchandising offer availability.',
            'group' => 'extras',
            'service' => 'air',
            'request' => 'AirMerchandisingOfferAvailabilityReq',
            'response' => 'AirMerchandisingOfferAvailabilityRsp',
            'status' => 'beta',
        ],
        'air_create_reservation' => [
            'label' => 'Create Reservation',
            'description' => 'Create air booking (Universal Record).',
            'group' => 'book',
            'service' => 'universal_record',
            'request' => 'AirCreateReservationReq',
            'response' => 'AirCreateReservationRsp',
            'status' => 'beta',
        ],
        'universal_record_retrieve' => [
            'label' => 'Retrieve PNR',
            'description' => 'Retrieve booking by Universal Record locator.',
            'group' => 'book',
            'service' => 'universal_record',
            'request' => 'UniversalRecordRetrieveReq',
            'response' => 'UniversalRecordRetrieveRsp',
            'status' => 'ready',
        ],
        'universal_record_cancel' => [
            'label' => 'Cancel PNR',
            'description' => 'Cancel Universal Record / booking.',
            'group' => 'book',
            'service' => 'universal_record',
            'request' => 'UniversalRecordCancelReq',
            'response' => 'UniversalRecordCancelRsp',
            'status' => 'ready',
        ],
        'air_ticketing' => [
            'label' => 'Issue Ticket',
            'description' => 'Ticket a stored booking.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirTicketingReq',
            'response' => 'AirTicketingRsp',
            'status' => 'beta',
        ],
        'air_retrieve_document' => [
            'label' => 'Retrieve Document',
            'description' => 'Retrieve ticket / document by locator.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirRetrieveDocumentReq',
            'response' => 'AirRetrieveDocumentRsp',
            'status' => 'beta',
        ],
        'air_void_ticket' => [
            'label' => 'Void Ticket',
            'description' => 'Void issued ticket.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirVoidTicketReq',
            'response' => 'AirVoidTicketRsp',
            'status' => 'beta',
        ],
        'air_refund_quote' => [
            'label' => 'Refund Quote',
            'description' => 'Quote refund for ticketed PNR.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirRefundQuoteReq',
            'response' => 'AirRefundQuoteRsp',
            'status' => 'beta',
        ],
        'air_cancel' => [
            'label' => 'Air Cancel',
            'description' => 'Cancel air segments on provider reservation.',
            'group' => 'manage',
            'service' => 'air',
            'request' => 'AirCancelReq',
            'response' => 'AirCancelRsp',
            'status' => 'beta',
        ],
        'air_exchange_quote' => [
            'label' => 'Exchange Quote',
            'description' => 'Quote exchange for ticketed itinerary.',
            'group' => 'manage',
            'service' => 'air',
            'request' => 'AirExchangeQuoteReq',
            'response' => 'AirExchangeQuoteRsp',
            'status' => 'beta',
        ],
        'air_exchange_ticketing' => [
            'label' => 'Exchange Ticketing',
            'description' => 'Complete exchange and reissue.',
            'group' => 'manage',
            'service' => 'air',
            'request' => 'AirExchangeTicketingReq',
            'response' => 'AirExchangeTicketingRsp',
            'status' => 'beta',
        ],
    ],
];
