<?php

/**
 * Travelport Universal API — flight (air) operations only.
 *
 * @see https://support.travelport.com/webhelp/uapi/Content/Getting_Started/Easy_Overview/Complete_Services_List.htm
 */
return [
    'groups' => [
        'shop' => [
            'label' => 'Search & compare',
            'description' => 'Find flights, schedules, and published fares before you book.',
            'icon' => 'fa-search',
            'order' => 1,
        ],
        'price' => [
            'label' => 'Price & rules',
            'description' => 'Confirm the exact sell price and read fare restrictions.',
            'icon' => 'fa-tag',
            'order' => 2,
        ],
        'book' => [
            'label' => 'Book & manage PNR',
            'description' => 'Create, view, or cancel a flight booking (passenger name record).',
            'icon' => 'fa-ticket-alt',
            'order' => 3,
        ],
        'ticket' => [
            'label' => 'Ticket & refund',
            'description' => 'Issue tickets, void, or refund after the booking is stored.',
            'icon' => 'fa-receipt',
            'order' => 4,
        ],
        'manage' => [
            'label' => 'Changes & exchanges',
            'description' => 'Modify or reissue ticketed itineraries.',
            'icon' => 'fa-exchange-alt',
            'order' => 5,
        ],
        'extras' => [
            'label' => 'Seats & add-ons',
            'description' => 'Seat maps and optional extras for a chosen flight.',
            'icon' => 'fa-chair',
            'order' => 6,
        ],
    ],

    'operations' => [
        'low_fare_search' => [
            'label' => 'Low Fare Search',
            'description' => 'Compare live bookable fares for your route and dates.',
            'help' => 'This is the main flight shopping tool. Enter origin, destination, and travel dates to see priced options from the GDS. Pick a result, then use Air Price to lock the fare before booking.',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'LowFareSearchReq',
            'response' => 'LowFareSearchRsp',
            'route' => 'search',
            'status' => 'ready',
        ],
        'availability_search' => [
            'label' => 'Availability Search',
            'description' => 'See which flights operate and how many seats are open.',
            'help' => 'Use when you need schedule and seat availability without full fare shopping. Helpful to check specific dates or flight numbers before quoting a customer.',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'AvailabilitySearchReq',
            'response' => 'AvailabilitySearchRsp',
            'status' => 'ready',
        ],
        'air_fare_display' => [
            'label' => 'Fare Display',
            'description' => 'List published tariff fares for a city pair (not live inventory).',
            'help' => 'Shows fare basis codes and amounts for a market, regardless of whether seats exist today. Use Fare Rules on a fare basis to see penalties, minimum stay, and advance purchase requirements.',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'AirFareDisplayReq',
            'response' => 'AirFareDisplayRsp',
            'status' => 'ready',
        ],
        'flight_time_table' => [
            'label' => 'Flight Timetable',
            'description' => 'Weekly flight schedules between two airports (no prices).',
            'help' => 'Returns operating days and times for direct (and optionally connecting) services over a date range. Ideal for planning; use Low Fare Search when you need a sellable price.',
            'group' => 'shop',
            'service' => 'air',
            'request' => 'FlightTimeTableReq',
            'response' => 'FlightTimeTableRsp',
            'status' => 'ready',
        ],
        'air_price' => [
            'label' => 'Air Price',
            'description' => 'Confirm the final price for an option from your last search.',
            'help' => 'Run Low Fare Search first in the same browser session, then open this page (or use Price & hold on a result). Air Price validates the itinerary and returns the amount to use when creating the booking.',
            'group' => 'price',
            'service' => 'air',
            'request' => 'AirPriceReq',
            'response' => 'AirPriceRsp',
            'status' => 'ready',
        ],
        'air_fare_rules' => [
            'label' => 'Fare Rules',
            'description' => 'Read penalties, changes, and restrictions for a fare basis.',
            'help' => 'Enter the fare basis (from Fare Display or a quote), plus origin and destination. Returns rule text such as cancellation fees, change conditions, and ticketing deadlines.',
            'group' => 'price',
            'service' => 'air',
            'request' => 'AirFareRulesReq',
            'response' => 'AirFareRulesRsp',
            'status' => 'ready',
        ],
        'air_reprice' => [
            'label' => 'Air Reprice',
            'description' => 'Refresh the price on a stored itinerary before ticketing.',
            'help' => 'Use when fares may have changed between booking and ticket issue. Requires an existing PNR or priced itinerary in the GDS.',
            'group' => 'price',
            'service' => 'air',
            'request' => 'AirRepriceReq',
            'response' => 'AirRepriceRsp',
            'status' => 'beta',
        ],
        'air_create_reservation' => [
            'label' => 'Create Reservation',
            'description' => 'Book flights and create a PNR for passengers.',
            'help' => 'Creates a Universal Record with air segments and travellers. You normally Air Price first, then pass passenger names and contact details. Full booking forms are being expanded.',
            'group' => 'book',
            'service' => 'universal_record',
            'request' => 'AirCreateReservationReq',
            'response' => 'AirCreateReservationRsp',
            'status' => 'beta',
        ],
        'universal_record_retrieve' => [
            'label' => 'Retrieve PNR',
            'description' => 'Open an existing booking by locator code.',
            'help' => 'Enter the Universal Record locator (e.g. from confirmation email) to view segments, passengers, and status. Use this before ticketing or making changes.',
            'group' => 'book',
            'service' => 'universal_record',
            'request' => 'UniversalRecordRetrieveReq',
            'response' => 'UniversalRecordRetrieveRsp',
            'status' => 'ready',
        ],
        'universal_record_cancel' => [
            'label' => 'Cancel PNR',
            'description' => 'Cancel the entire booking in the GDS.',
            'help' => 'Voids the Universal Record and associated air reservation. Use the locator from Retrieve PNR. Irreversible once completed—confirm with the customer first.',
            'group' => 'book',
            'service' => 'universal_record',
            'request' => 'UniversalRecordCancelReq',
            'response' => 'UniversalRecordCancelRsp',
            'status' => 'ready',
        ],
        'air_ticketing' => [
            'label' => 'Issue Ticket',
            'description' => 'Ticket a confirmed reservation and issue e-tickets.',
            'help' => 'Issues electronic tickets for all passengers on the PNR. The booking must be priced and ready to ticket; use Retrieve PNR to verify status first.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirTicketingReq',
            'response' => 'AirTicketingRsp',
            'status' => 'beta',
        ],
        'air_retrieve_document' => [
            'label' => 'Retrieve Ticket',
            'description' => 'Download e-ticket or EMD document details.',
            'help' => 'Fetches ticket numbers and coupon status after issue. Use the booking locator or ticket number from Issue Ticket.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirRetrieveDocumentReq',
            'response' => 'AirRetrieveDocumentRsp',
            'status' => 'beta',
        ],
        'air_void_ticket' => [
            'label' => 'Void Ticket',
            'description' => 'Void tickets issued the same day (where allowed).',
            'help' => 'Cancels an issued ticket before end of day in many markets. Not all fares allow void—check fare rules and airline policy.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirVoidTicketReq',
            'response' => 'AirVoidTicketRsp',
            'status' => 'beta',
        ],
        'air_refund_quote' => [
            'label' => 'Refund Quote',
            'description' => 'Estimate how much is refundable before processing.',
            'help' => 'Returns refundable amount and penalties for a ticketed booking. Run this before Refund Ticket to advise the customer.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirRefundQuoteReq',
            'response' => 'AirRefundQuoteRsp',
            'status' => 'beta',
        ],
        'air_refund' => [
            'label' => 'Refund Ticket',
            'description' => 'Process a refund to the original form of payment.',
            'help' => 'Completes the refund after the customer accepts the quote. May take several days to appear on the card depending on the airline.',
            'group' => 'ticket',
            'service' => 'air',
            'request' => 'AirRefundReq',
            'response' => 'AirRefundRsp',
            'status' => 'beta',
        ],
        'air_cancel' => [
            'label' => 'Cancel Segments',
            'description' => 'Remove air segments from a booking without cancelling the whole PNR.',
            'help' => 'Use when only part of the trip should be cancelled. For a full cancellation, Cancel PNR is usually simpler.',
            'group' => 'manage',
            'service' => 'air',
            'request' => 'AirCancelReq',
            'response' => 'AirCancelRsp',
            'status' => 'beta',
        ],
        'air_exchange_quote' => [
            'label' => 'Exchange Quote',
            'description' => 'Quote change fees and fare difference for a new itinerary.',
            'help' => 'Shows cost to change dates or routing on a ticketed booking. Accept the quote with Exchange, then Exchange Ticketing to reissue.',
            'group' => 'manage',
            'service' => 'air',
            'request' => 'AirExchangeQuoteReq',
            'response' => 'AirExchangeQuoteRsp',
            'status' => 'beta',
        ],
        'air_exchange' => [
            'label' => 'Exchange',
            'description' => 'Apply an itinerary change to a ticketed booking.',
            'help' => 'Replaces or adds segments after an Exchange Quote. Must be followed by Exchange Ticketing to issue new tickets.',
            'group' => 'manage',
            'service' => 'air',
            'request' => 'AirExchangeReq',
            'response' => 'AirExchangeRsp',
            'status' => 'beta',
        ],
        'air_exchange_ticketing' => [
            'label' => 'Exchange Ticketing',
            'description' => 'Issue new tickets after an exchange is stored.',
            'help' => 'Final step of the exchange workflow. Run after Exchange succeeds and any additional collection is approved.',
            'group' => 'manage',
            'service' => 'air',
            'request' => 'AirExchangeTicketingReq',
            'response' => 'AirExchangeTicketingRsp',
            'status' => 'beta',
        ],
        'seat_map' => [
            'label' => 'Seat Map',
            'description' => 'View seat layout and availability on a specific flight.',
            'help' => 'Enter airline, flight number, route, and departure time from availability or a booking. Use before assigning seats or selling paid seats.',
            'group' => 'extras',
            'service' => 'air',
            'request' => 'SeatMapReq',
            'response' => 'SeatMapRsp',
            'status' => 'ready',
        ],
        'air_merchandising' => [
            'label' => 'Ancillaries',
            'description' => 'Shop bags, seats, and bundles for a priced itinerary.',
            'help' => 'Returns optional services offered by the airline for your selected flights. Often used after Air Price and before Create Reservation.',
            'group' => 'extras',
            'service' => 'air',
            'request' => 'AirMerchandisingOfferAvailabilityReq',
            'response' => 'AirMerchandisingOfferAvailabilityRsp',
            'status' => 'beta',
        ],
        'air_pre_pay' => [
            'label' => 'Pre-paid services',
            'description' => 'Pay for seats or services in advance of travel.',
            'help' => 'Books prepaid ancillaries tied to the PNR. Requires a confirmed booking and supported carrier.',
            'group' => 'extras',
            'service' => 'air',
            'request' => 'AirPrePayReq',
            'response' => 'AirPrePayRsp',
            'status' => 'beta',
        ],
    ],
];
